// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: vivo_rta.proto

package vivo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId  string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Did        string `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	PositionId string `protobuf:"bytes,3,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Model      string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Location   string `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	UserLabel  string `protobuf:"bytes,6,opt,name=user_label,json=userLabel,proto3" json:"user_label,omitempty"`
	DidType    int32  `protobuf:"varint,7,opt,name=did_type,json=didType,proto3" json:"did_type,omitempty"`
	Ip         string `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip,omitempty"`
	Ua         string `protobuf:"bytes,9,opt,name=ua,proto3" json:"ua,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vivo_rta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_vivo_rta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_vivo_rta_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Request) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *Request) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *Request) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Request) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Request) GetUserLabel() string {
	if x != nil {
		return x.UserLabel
	}
	return ""
}

func (x *Request) GetDidType() int32 {
	if x != nil {
		return x.DidType
	}
	return 0
}

func (x *Request) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Request) GetUa() string {
	if x != nil {
		return x.Ua
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code              int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	IsPutin           bool     `protobuf:"varint,2,opt,name=is_putin,json=isPutin,proto3" json:"is_putin,omitempty"`
	AdvertiserAccount []string `protobuf:"bytes,3,rep,name=advertiser_account,json=advertiserAccount,proto3" json:"advertiser_account,omitempty"`
	CacheTime         int32    `protobuf:"varint,5,opt,name=cache_time,json=cacheTime,proto3" json:"cache_time,omitempty"`
	Ac                bool     `protobuf:"varint,8,opt,name=ac,proto3" json:"ac,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vivo_rta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_vivo_rta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_vivo_rta_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetIsPutin() bool {
	if x != nil {
		return x.IsPutin
	}
	return false
}

func (x *Response) GetAdvertiserAccount() []string {
	if x != nil {
		return x.AdvertiserAccount
	}
	return nil
}

func (x *Response) GetCacheTime() int32 {
	if x != nil {
		return x.CacheTime
	}
	return 0
}

func (x *Response) GetAc() bool {
	if x != nil {
		return x.Ac
	}
	return false
}

var File_vivo_rta_proto protoreflect.FileDescriptor

var file_vivo_rta_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x76, 0x69, 0x76, 0x6f, 0x5f, 0x72, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x76, 0x69, 0x76, 0x6f, 0x22, 0xe7, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x64, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x69, 0x64, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x69, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x75, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x75, 0x61,
	0x22, 0x97, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x70, 0x75, 0x74, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x50, 0x75, 0x74, 0x69, 0x6e, 0x12, 0x2d, 0x0a, 0x12,
	0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x63, 0x61, 0x63, 0x68, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x61, 0x63,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x61, 0x63, 0x42, 0x1c, 0x5a, 0x1a, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x78, 0x70, 0x6f, 0x73,
	0x75, 0x72, 0x65, 0x2f, 0x76, 0x69, 0x76, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vivo_rta_proto_rawDescOnce sync.Once
	file_vivo_rta_proto_rawDescData = file_vivo_rta_proto_rawDesc
)

func file_vivo_rta_proto_rawDescGZIP() []byte {
	file_vivo_rta_proto_rawDescOnce.Do(func() {
		file_vivo_rta_proto_rawDescData = protoimpl.X.CompressGZIP(file_vivo_rta_proto_rawDescData)
	})
	return file_vivo_rta_proto_rawDescData
}

var file_vivo_rta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vivo_rta_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: vivo.Request
	(*Response)(nil), // 1: vivo.Response
}
var file_vivo_rta_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vivo_rta_proto_init() }
func file_vivo_rta_proto_init() {
	if File_vivo_rta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vivo_rta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vivo_rta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vivo_rta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vivo_rta_proto_goTypes,
		DependencyIndexes: file_vivo_rta_proto_depIdxs,
		MessageInfos:      file_vivo_rta_proto_msgTypes,
	}.Build()
	File_vivo_rta_proto = out.File
	file_vivo_rta_proto_rawDesc = nil
	file_vivo_rta_proto_goTypes = nil
	file_vivo_rta_proto_depIdxs = nil
}
