// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: baidu_rta.proto

package baidu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResType int32

const (
	ResType_ALL  ResType = 0 // 全部投放
	ResType_NONE ResType = 1 // 全部不投
	ResType_PART ResType = 2 // 只投放指定部分
)

// Enum value maps for ResType.
var (
	ResType_name = map[int32]string{
		0: "ALL",
		1: "NONE",
		2: "PART",
	}
	ResType_value = map[string]int32{
		"ALL":  0,
		"NONE": 1,
		"PART": 2,
	}
)

func (x ResType) Enum() *ResType {
	p := new(ResType)
	*p = x
	return p
}

func (x ResType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResType) Descriptor() protoreflect.EnumDescriptor {
	return file_baidu_rta_proto_enumTypes[0].Descriptor()
}

func (ResType) Type() protoreflect.EnumType {
	return &file_baidu_rta_proto_enumTypes[0]
}

func (x ResType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ResType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ResType(num)
	return nil
}

// Deprecated: Use ResType.Descriptor instead.
func (ResType) EnumDescriptor() ([]byte, []int) {
	return file_baidu_rta_proto_rawDescGZIP(), []int{0}
}

type OsType int32

const (
	OsType_UNKNOWN OsType = 0 // 类型未知
	OsType_ANDROID OsType = 1 // android
	OsType_IOS     OsType = 2 // ios
)

// Enum value maps for OsType.
var (
	OsType_name = map[int32]string{
		0: "UNKNOWN",
		1: "ANDROID",
		2: "IOS",
	}
	OsType_value = map[string]int32{
		"UNKNOWN": 0,
		"ANDROID": 1,
		"IOS":     2,
	}
)

func (x OsType) Enum() *OsType {
	p := new(OsType)
	*p = x
	return p
}

func (x OsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OsType) Descriptor() protoreflect.EnumDescriptor {
	return file_baidu_rta_proto_enumTypes[1].Descriptor()
}

func (OsType) Type() protoreflect.EnumType {
	return &file_baidu_rta_proto_enumTypes[1]
}

func (x OsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OsType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OsType(num)
	return nil
}

// Deprecated: Use OsType.Descriptor instead.
func (OsType) EnumDescriptor() ([]byte, []int) {
	return file_baidu_rta_proto_rawDescGZIP(), []int{1}
}

type AndroidDeviceIdType int32

const (
	AndroidDeviceIdType_IMEI AndroidDeviceIdType = 1
	AndroidDeviceIdType_OAID AndroidDeviceIdType = 2
)

// Enum value maps for AndroidDeviceIdType.
var (
	AndroidDeviceIdType_name = map[int32]string{
		1: "IMEI",
		2: "OAID",
	}
	AndroidDeviceIdType_value = map[string]int32{
		"IMEI": 1,
		"OAID": 2,
	}
)

func (x AndroidDeviceIdType) Enum() *AndroidDeviceIdType {
	p := new(AndroidDeviceIdType)
	*p = x
	return p
}

func (x AndroidDeviceIdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AndroidDeviceIdType) Descriptor() protoreflect.EnumDescriptor {
	return file_baidu_rta_proto_enumTypes[2].Descriptor()
}

func (AndroidDeviceIdType) Type() protoreflect.EnumType {
	return &file_baidu_rta_proto_enumTypes[2]
}

func (x AndroidDeviceIdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AndroidDeviceIdType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AndroidDeviceIdType(num)
	return nil
}

// Deprecated: Use AndroidDeviceIdType.Descriptor instead.
func (AndroidDeviceIdType) EnumDescriptor() ([]byte, []int) {
	return file_baidu_rta_proto_rawDescGZIP(), []int{2}
}

type DeviceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdfaMd5      *string `protobuf:"bytes,1,opt,name=idfa_md5,json=idfaMd5" json:"idfa_md5,omitempty"`
	ImeiMd5      *string `protobuf:"bytes,2,opt,name=imei_md5,json=imeiMd5" json:"imei_md5,omitempty"`
	AndroidIdMd5 *string `protobuf:"bytes,3,opt,name=android_id_md5,json=androidIdMd5" json:"android_id_md5,omitempty"`
	OaidMd5      *string `protobuf:"bytes,4,opt,name=oaid_md5,json=oaidMd5" json:"oaid_md5,omitempty"`
	UserIpV4     *string `protobuf:"bytes,5,opt,name=user_ip_v4,json=userIpV4" json:"user_ip_v4,omitempty"`
	UserIpV6     *string `protobuf:"bytes,6,opt,name=user_ip_v6,json=userIpV6" json:"user_ip_v6,omitempty"`
	Oaid         *string `protobuf:"bytes,7,opt,name=oaid" json:"oaid,omitempty"`
	Idfa         *string `protobuf:"bytes,8,opt,name=idfa" json:"idfa,omitempty"`
	UserAgent    *string `protobuf:"bytes,11,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	Imei2Md5     *string `protobuf:"bytes,12,opt,name=imei2_md5,json=imei2Md5" json:"imei2_md5,omitempty"`
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_baidu_rta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_baidu_rta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_baidu_rta_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetIdfaMd5() string {
	if x != nil && x.IdfaMd5 != nil {
		return *x.IdfaMd5
	}
	return ""
}

func (x *DeviceInfo) GetImeiMd5() string {
	if x != nil && x.ImeiMd5 != nil {
		return *x.ImeiMd5
	}
	return ""
}

func (x *DeviceInfo) GetAndroidIdMd5() string {
	if x != nil && x.AndroidIdMd5 != nil {
		return *x.AndroidIdMd5
	}
	return ""
}

func (x *DeviceInfo) GetOaidMd5() string {
	if x != nil && x.OaidMd5 != nil {
		return *x.OaidMd5
	}
	return ""
}

func (x *DeviceInfo) GetUserIpV4() string {
	if x != nil && x.UserIpV4 != nil {
		return *x.UserIpV4
	}
	return ""
}

func (x *DeviceInfo) GetUserIpV6() string {
	if x != nil && x.UserIpV6 != nil {
		return *x.UserIpV6
	}
	return ""
}

func (x *DeviceInfo) GetOaid() string {
	if x != nil && x.Oaid != nil {
		return *x.Oaid
	}
	return ""
}

func (x *DeviceInfo) GetIdfa() string {
	if x != nil && x.Idfa != nil {
		return *x.Idfa
	}
	return ""
}

func (x *DeviceInfo) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *DeviceInfo) GetImei2Md5() string {
	if x != nil && x.Imei2Md5 != nil {
		return *x.Imei2Md5
	}
	return ""
}

type RtaApiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Qid               *uint64              `protobuf:"varint,1,req,name=qid" json:"qid,omitempty"`                                                                                       // 请求唯一标识
	OsType            *OsType              `protobuf:"varint,2,req,name=os_type,json=osType,enum=baidu.OsType" json:"os_type,omitempty"`                                                 // 操作系统类型:
	DeviceIdMd5       *string              `protobuf:"bytes,3,req,name=device_id_md5,json=deviceIdMd5" json:"device_id_md5,omitempty"`                                                   // 设备号的 md5, 设备号安卓为 imei 或 oaid（通过 android_device_type 区分），ios 为 idfa
	SignTime          *uint64              `protobuf:"varint,4,req,name=sign_time,json=signTime" json:"sign_time,omitempty"`                                                             // 调用的时间戳, 1970-01-01 后的毫秒数
	Token             *string              `protobuf:"bytes,5,req,name=token" json:"token,omitempty"`                                                                                    // 验证令牌，其值为 md5(qid+sign_time+客户独有标识)
	AndroidDeviceType *AndroidDeviceIdType `protobuf:"varint,6,opt,name=android_device_type,json=androidDeviceType,enum=baidu.AndroidDeviceIdType" json:"android_device_type,omitempty"` // android device type 用于区分 imei 或 oaid，可选
	RtaIds            []uint64             `protobuf:"varint,7,rep,name=rta_ids,json=rtaIds" json:"rta_ids,omitempty"`                                                                   // 本次请求的策略 id 列表, DPA 请求中暂无该字段
	DeviceInfo        *DeviceInfo          `protobuf:"bytes,8,opt,name=device_info,json=deviceInfo" json:"device_info,omitempty"`                                                        // 用户设备信息
}

func (x *RtaApiRequest) Reset() {
	*x = RtaApiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_baidu_rta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtaApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtaApiRequest) ProtoMessage() {}

func (x *RtaApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baidu_rta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtaApiRequest.ProtoReflect.Descriptor instead.
func (*RtaApiRequest) Descriptor() ([]byte, []int) {
	return file_baidu_rta_proto_rawDescGZIP(), []int{1}
}

func (x *RtaApiRequest) GetQid() uint64 {
	if x != nil && x.Qid != nil {
		return *x.Qid
	}
	return 0
}

func (x *RtaApiRequest) GetOsType() OsType {
	if x != nil && x.OsType != nil {
		return *x.OsType
	}
	return OsType_UNKNOWN
}

func (x *RtaApiRequest) GetDeviceIdMd5() string {
	if x != nil && x.DeviceIdMd5 != nil {
		return *x.DeviceIdMd5
	}
	return ""
}

func (x *RtaApiRequest) GetSignTime() uint64 {
	if x != nil && x.SignTime != nil {
		return *x.SignTime
	}
	return 0
}

func (x *RtaApiRequest) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *RtaApiRequest) GetAndroidDeviceType() AndroidDeviceIdType {
	if x != nil && x.AndroidDeviceType != nil {
		return *x.AndroidDeviceType
	}
	return AndroidDeviceIdType_IMEI
}

func (x *RtaApiRequest) GetRtaIds() []uint64 {
	if x != nil {
		return x.RtaIds
	}
	return nil
}

func (x *RtaApiRequest) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type AdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId *uint64  `protobuf:"varint,1,req,name=account_id,json=accountId" json:"account_id,omitempty"` // 账户 id，百度方分配的账户 id
	UnitId    []uint64 `protobuf:"varint,2,rep,name=unit_id,json=unitId" json:"unit_id,omitempty"`          // 广告单元 id
}

func (x *AdResult) Reset() {
	*x = AdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_baidu_rta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdResult) ProtoMessage() {}

func (x *AdResult) ProtoReflect() protoreflect.Message {
	mi := &file_baidu_rta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdResult.ProtoReflect.Descriptor instead.
func (*AdResult) Descriptor() ([]byte, []int) {
	return file_baidu_rta_proto_rawDescGZIP(), []int{2}
}

func (x *AdResult) GetAccountId() uint64 {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return 0
}

func (x *AdResult) GetUnitId() []uint64 {
	if x != nil {
		return x.UnitId
	}
	return nil
}

type RtaStrategyAdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RtaId *uint64 `protobuf:"varint,1,req,name=rta_id,json=rtaId" json:"rta_id,omitempty"`
}

func (x *RtaStrategyAdResult) Reset() {
	*x = RtaStrategyAdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_baidu_rta_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtaStrategyAdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtaStrategyAdResult) ProtoMessage() {}

func (x *RtaStrategyAdResult) ProtoReflect() protoreflect.Message {
	mi := &file_baidu_rta_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtaStrategyAdResult.ProtoReflect.Descriptor instead.
func (*RtaStrategyAdResult) Descriptor() ([]byte, []int) {
	return file_baidu_rta_proto_rawDescGZIP(), []int{3}
}

func (x *RtaStrategyAdResult) GetRtaId() uint64 {
	if x != nil && x.RtaId != nil {
		return *x.RtaId
	}
	return 0
}

type RtaApiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Qid             *uint64                `protobuf:"varint,1,req,name=qid" json:"qid,omitempty"`
	Res             *ResType               `protobuf:"varint,2,req,name=res,enum=baidu.ResType" json:"res,omitempty"`
	UserScore       *uint32                `protobuf:"varint,3,opt,name=user_score,json=userScore" json:"user_score,omitempty"` // 客户打分，可选，DPA 暂不可用
	AdResults       []*AdResult            `protobuf:"bytes,4,rep,name=ad_results,json=adResults" json:"ad_results,omitempty"`  // 指定要出的广告组，可选
	StrategyResults []*RtaStrategyAdResult `protobuf:"bytes,5,rep,name=strategy_results,json=strategyResults" json:"strategy_results,omitempty"`
}

func (x *RtaApiResponse) Reset() {
	*x = RtaApiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_baidu_rta_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtaApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtaApiResponse) ProtoMessage() {}

func (x *RtaApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baidu_rta_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtaApiResponse.ProtoReflect.Descriptor instead.
func (*RtaApiResponse) Descriptor() ([]byte, []int) {
	return file_baidu_rta_proto_rawDescGZIP(), []int{4}
}

func (x *RtaApiResponse) GetQid() uint64 {
	if x != nil && x.Qid != nil {
		return *x.Qid
	}
	return 0
}

func (x *RtaApiResponse) GetRes() ResType {
	if x != nil && x.Res != nil {
		return *x.Res
	}
	return ResType_ALL
}

func (x *RtaApiResponse) GetUserScore() uint32 {
	if x != nil && x.UserScore != nil {
		return *x.UserScore
	}
	return 0
}

func (x *RtaApiResponse) GetAdResults() []*AdResult {
	if x != nil {
		return x.AdResults
	}
	return nil
}

func (x *RtaApiResponse) GetStrategyResults() []*RtaStrategyAdResult {
	if x != nil {
		return x.StrategyResults
	}
	return nil
}

var File_baidu_rta_proto protoreflect.FileDescriptor

var file_baidu_rta_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x62, 0x61, 0x69, 0x64, 0x75, 0x5f, 0x72, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x62, 0x61, 0x69, 0x64, 0x75, 0x22, 0xa3, 0x02, 0x0a, 0x0a, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x64, 0x66, 0x61, 0x5f,
	0x6d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x64, 0x66, 0x61, 0x4d,
	0x64, 0x35, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6d, 0x65, 0x69, 0x5f, 0x6d, 0x64, 0x35, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6d, 0x65, 0x69, 0x4d, 0x64, 0x35, 0x12, 0x24, 0x0a,
	0x0e, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x5f, 0x69, 0x64, 0x5f, 0x6d, 0x64, 0x35, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x49, 0x64,
	0x4d, 0x64, 0x35, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x61, 0x69, 0x64, 0x5f, 0x6d, 0x64, 0x35, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x61, 0x69, 0x64, 0x4d, 0x64, 0x35, 0x12, 0x1c,
	0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x70, 0x5f, 0x76, 0x34, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x70, 0x56, 0x34, 0x12, 0x1c, 0x0a, 0x0a,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x70, 0x5f, 0x76, 0x36, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x70, 0x56, 0x36, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x61,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x61, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x69, 0x64, 0x66, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x64,
	0x66, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x65, 0x69, 0x32, 0x5f, 0x6d, 0x64, 0x35, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x65, 0x69, 0x32, 0x4d, 0x64, 0x35, 0x22, 0xb9,
	0x02, 0x0a, 0x0d, 0x52, 0x74, 0x61, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x71, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x03, 0x71,
	0x69, 0x64, 0x12, 0x26, 0x0a, 0x07, 0x6f, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x62, 0x61, 0x69, 0x64, 0x75, 0x2e, 0x4f, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x06, 0x6f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x6d, 0x64, 0x35, 0x18, 0x03, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x4d, 0x64, 0x35, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28,
	0x04, 0x52, 0x08, 0x73, 0x69, 0x67, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x4a, 0x0a, 0x13, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x5f, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a,
	0x2e, 0x62, 0x61, 0x69, 0x64, 0x75, 0x2e, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x11, 0x61, 0x6e, 0x64, 0x72,
	0x6f, 0x69, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06,
	0x72, 0x74, 0x61, 0x49, 0x64, 0x73, 0x12, 0x32, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x61,
	0x69, 0x64, 0x75, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x42, 0x0a, 0x08, 0x41, 0x64,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x22, 0x2c,
	0x0a, 0x13, 0x52, 0x74, 0x61, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x41, 0x64, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x05, 0x72, 0x74, 0x61, 0x49, 0x64, 0x22, 0xda, 0x01, 0x0a,
	0x0e, 0x52, 0x74, 0x61, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x71, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x03, 0x71, 0x69,
	0x64, 0x12, 0x20, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x0e,
	0x2e, 0x62, 0x61, 0x69, 0x64, 0x75, 0x2e, 0x52, 0x65, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03,
	0x72, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x61, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x69, 0x64, 0x75, 0x2e, 0x41,
	0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x09, 0x61, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x12, 0x45, 0x0a, 0x10, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x5f, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62,
	0x61, 0x69, 0x64, 0x75, 0x2e, 0x52, 0x74, 0x61, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79,
	0x41, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x2a, 0x26, 0x0a, 0x07, 0x52, 0x65, 0x73,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x41, 0x52, 0x54, 0x10,
	0x02, 0x2a, 0x2b, 0x0a, 0x06, 0x4f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x4e, 0x44, 0x52,
	0x4f, 0x49, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4f, 0x53, 0x10, 0x02, 0x2a, 0x29,
	0x0a, 0x13, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4d, 0x45, 0x49, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x4f, 0x41, 0x49, 0x44, 0x10, 0x02, 0x42, 0x1d, 0x5a, 0x1b, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x75,
	0x72, 0x65, 0x2f, 0x62, 0x61, 0x69, 0x64, 0x75,
}

var (
	file_baidu_rta_proto_rawDescOnce sync.Once
	file_baidu_rta_proto_rawDescData = file_baidu_rta_proto_rawDesc
)

func file_baidu_rta_proto_rawDescGZIP() []byte {
	file_baidu_rta_proto_rawDescOnce.Do(func() {
		file_baidu_rta_proto_rawDescData = protoimpl.X.CompressGZIP(file_baidu_rta_proto_rawDescData)
	})
	return file_baidu_rta_proto_rawDescData
}

var file_baidu_rta_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_baidu_rta_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_baidu_rta_proto_goTypes = []interface{}{
	(ResType)(0),                // 0: baidu.ResType
	(OsType)(0),                 // 1: baidu.OsType
	(AndroidDeviceIdType)(0),    // 2: baidu.AndroidDeviceIdType
	(*DeviceInfo)(nil),          // 3: baidu.DeviceInfo
	(*RtaApiRequest)(nil),       // 4: baidu.RtaApiRequest
	(*AdResult)(nil),            // 5: baidu.AdResult
	(*RtaStrategyAdResult)(nil), // 6: baidu.RtaStrategyAdResult
	(*RtaApiResponse)(nil),      // 7: baidu.RtaApiResponse
}
var file_baidu_rta_proto_depIdxs = []int32{
	1, // 0: baidu.RtaApiRequest.os_type:type_name -> baidu.OsType
	2, // 1: baidu.RtaApiRequest.android_device_type:type_name -> baidu.AndroidDeviceIdType
	3, // 2: baidu.RtaApiRequest.device_info:type_name -> baidu.DeviceInfo
	0, // 3: baidu.RtaApiResponse.res:type_name -> baidu.ResType
	5, // 4: baidu.RtaApiResponse.ad_results:type_name -> baidu.AdResult
	6, // 5: baidu.RtaApiResponse.strategy_results:type_name -> baidu.RtaStrategyAdResult
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_baidu_rta_proto_init() }
func file_baidu_rta_proto_init() {
	if File_baidu_rta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_baidu_rta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_baidu_rta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtaApiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_baidu_rta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_baidu_rta_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtaStrategyAdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_baidu_rta_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtaApiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_baidu_rta_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_baidu_rta_proto_goTypes,
		DependencyIndexes: file_baidu_rta_proto_depIdxs,
		EnumInfos:         file_baidu_rta_proto_enumTypes,
		MessageInfos:      file_baidu_rta_proto_msgTypes,
	}.Build()
	File_baidu_rta_proto = out.File
	file_baidu_rta_proto_rawDesc = nil
	file_baidu_rta_proto_goTypes = nil
	file_baidu_rta_proto_depIdxs = nil
}
