// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: qutoutiao_rta.proto

package qutoutiao

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OSType int32

const (
	OSType_OS_UNKNOWN OSType = 0
	OSType_ANDROID    OSType = 1
	OSType_IOS        OSType = 2
)

// Enum value maps for OSType.
var (
	OSType_name = map[int32]string{
		0: "OS_UNKNOWN",
		1: "ANDROID",
		2: "IOS",
	}
	OSType_value = map[string]int32{
		"OS_UNKNOWN": 0,
		"ANDROID":    1,
		"IOS":        2,
	}
)

func (x OSType) Enum() *OSType {
	p := new(OSType)
	*p = x
	return p
}

func (x OSType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OSType) Descriptor() protoreflect.EnumDescriptor {
	return file_qutoutiao_rta_proto_enumTypes[0].Descriptor()
}

func (OSType) Type() protoreflect.EnumType {
	return &file_qutoutiao_rta_proto_enumTypes[0]
}

func (x OSType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OSType.Descriptor instead.
func (OSType) EnumDescriptor() ([]byte, []int) {
	return file_qutoutiao_rta_proto_rawDescGZIP(), []int{0}
}

type DeviceIdType int32

const (
	DeviceIdType_DEVID_UNKNOWN DeviceIdType = 0
	DeviceIdType_IMEI          DeviceIdType = 1
	DeviceIdType_IDFA          DeviceIdType = 2
	DeviceIdType_ANDROIDID     DeviceIdType = 3
	DeviceIdType_MEID          DeviceIdType = 4
	DeviceIdType_OAID          DeviceIdType = 5
	DeviceIdType_TUID          DeviceIdType = 6
)

// Enum value maps for DeviceIdType.
var (
	DeviceIdType_name = map[int32]string{
		0: "DEVID_UNKNOWN",
		1: "IMEI",
		2: "IDFA",
		3: "ANDROIDID",
		4: "MEID",
		5: "OAID",
		6: "TUID",
	}
	DeviceIdType_value = map[string]int32{
		"DEVID_UNKNOWN": 0,
		"IMEI":          1,
		"IDFA":          2,
		"ANDROIDID":     3,
		"MEID":          4,
		"OAID":          5,
		"TUID":          6,
	}
)

func (x DeviceIdType) Enum() *DeviceIdType {
	p := new(DeviceIdType)
	*p = x
	return p
}

func (x DeviceIdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceIdType) Descriptor() protoreflect.EnumDescriptor {
	return file_qutoutiao_rta_proto_enumTypes[1].Descriptor()
}

func (DeviceIdType) Type() protoreflect.EnumType {
	return &file_qutoutiao_rta_proto_enumTypes[1]
}

func (x DeviceIdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceIdType.Descriptor instead.
func (DeviceIdType) EnumDescriptor() ([]byte, []int) {
	return file_qutoutiao_rta_proto_rawDescGZIP(), []int{1}
}

type StatusCode int32

const (
	StatusCode_BID_ALL          StatusCode = 0 //全部参与竞价
	StatusCode_BID_ABANDON      StatusCode = 1 //全部放弃竞价
	StatusCode_BID_EXCLUDE_PART StatusCode = 2 //部分id 不参与竞价
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "BID_ALL",
		1: "BID_ABANDON",
		2: "BID_EXCLUDE_PART",
	}
	StatusCode_value = map[string]int32{
		"BID_ALL":          0,
		"BID_ABANDON":      1,
		"BID_EXCLUDE_PART": 2,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_qutoutiao_rta_proto_enumTypes[2].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_qutoutiao_rta_proto_enumTypes[2]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_qutoutiao_rta_proto_rawDescGZIP(), []int{2}
}

type DeviceId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  DeviceIdType `protobuf:"varint,1,opt,name=type,proto3,enum=qutoutiao.DeviceIdType" json:"type,omitempty"` //设备ID 的类型
	Id    string       `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                  //设备ID
	IsMd5 bool         `protobuf:"varint,3,opt,name=is_md5,json=isMd5,proto3" json:"is_md5,omitempty"`              //设备ID 是否md5 加密
}

func (x *DeviceId) Reset() {
	*x = DeviceId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qutoutiao_rta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceId) ProtoMessage() {}

func (x *DeviceId) ProtoReflect() protoreflect.Message {
	mi := &file_qutoutiao_rta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceId.ProtoReflect.Descriptor instead.
func (*DeviceId) Descriptor() ([]byte, []int) {
	return file_qutoutiao_rta_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceId) GetType() DeviceIdType {
	if x != nil {
		return x.Type
	}
	return DeviceIdType_DEVID_UNKNOWN
}

func (x *DeviceId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceId) GetIsMd5() bool {
	if x != nil {
		return x.IsMd5
	}
	return false
}

type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Os    OSType      `protobuf:"varint,1,opt,name=os,proto3,enum=qutoutiao.OSType" json:"os,omitempty"` //操作系统
	DevId []*DeviceId `protobuf:"bytes,2,rep,name=dev_id,json=devId,proto3" json:"dev_id,omitempty"`     //设备ID
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qutoutiao_rta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_qutoutiao_rta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_qutoutiao_rta_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetOs() OSType {
	if x != nil {
		return x.Os
	}
	return OSType_OS_UNKNOWN
}

func (x *Device) GetDevId() []*DeviceId {
	if x != nil {
		return x.DevId
	}
	return nil
}

type RTARequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId  string  `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`    //请求ID， 请求唯一标识
	SlotId string  `protobuf:"bytes,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"` //当前流量的广告位
	Device *Device `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`               //设备相关信息
}

func (x *RTARequest) Reset() {
	*x = RTARequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qutoutiao_rta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RTARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTARequest) ProtoMessage() {}

func (x *RTARequest) ProtoReflect() protoreflect.Message {
	mi := &file_qutoutiao_rta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTARequest.ProtoReflect.Descriptor instead.
func (*RTARequest) Descriptor() ([]byte, []int) {
	return file_qutoutiao_rta_proto_rawDescGZIP(), []int{2}
}

func (x *RTARequest) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *RTARequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *RTARequest) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type RTAResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode    StatusCode `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=qutoutiao.StatusCode" json:"status_code,omitempty"` //状态码
	ExcludeUserId []int64    `protobuf:"varint,2,rep,packed,name=exclude_user_id,json=excludeUserId,proto3" json:"exclude_user_id,omitempty"`         //不参与竞价的user id
	ExcludeUnitId []int64    `protobuf:"varint,3,rep,packed,name=exclude_unit_id,json=excludeUnitId,proto3" json:"exclude_unit_id,omitempty"`         //不参与竞价的unit id
	CostTime      int64      `protobuf:"varint,4,opt,name=cost_time,json=costTime,proto3" json:"cost_time,omitempty"`                                 //广告主内部耗时，单位秒
}

func (x *RTAResponse) Reset() {
	*x = RTAResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qutoutiao_rta_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RTAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTAResponse) ProtoMessage() {}

func (x *RTAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qutoutiao_rta_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTAResponse.ProtoReflect.Descriptor instead.
func (*RTAResponse) Descriptor() ([]byte, []int) {
	return file_qutoutiao_rta_proto_rawDescGZIP(), []int{3}
}

func (x *RTAResponse) GetStatusCode() StatusCode {
	if x != nil {
		return x.StatusCode
	}
	return StatusCode_BID_ALL
}

func (x *RTAResponse) GetExcludeUserId() []int64 {
	if x != nil {
		return x.ExcludeUserId
	}
	return nil
}

func (x *RTAResponse) GetExcludeUnitId() []int64 {
	if x != nil {
		return x.ExcludeUnitId
	}
	return nil
}

func (x *RTAResponse) GetCostTime() int64 {
	if x != nil {
		return x.CostTime
	}
	return 0
}

var File_qutoutiao_rta_proto protoreflect.FileDescriptor

var file_qutoutiao_rta_proto_rawDesc = []byte{
	0x0a, 0x13, 0x71, 0x75, 0x74, 0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f, 0x5f, 0x72, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x71, 0x75, 0x74, 0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f,
	0x22, 0x5e, 0x0a, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x71, 0x75, 0x74,
	0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f,
	0x6d, 0x64, 0x35, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x4d, 0x64, 0x35,
	0x22, 0x57, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x02, 0x6f, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x71, 0x75, 0x74, 0x6f, 0x75, 0x74, 0x69,
	0x61, 0x6f, 0x2e, 0x4f, 0x53, 0x54, 0x79, 0x70, 0x65, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x2a, 0x0a,
	0x06, 0x64, 0x65, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x71, 0x75, 0x74, 0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x52, 0x05, 0x64, 0x65, 0x76, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x0a, 0x52, 0x54, 0x41,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x71, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x71, 0x75, 0x74, 0x6f, 0x75, 0x74,
	0x69, 0x61, 0x6f, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x22, 0xb2, 0x01, 0x0a, 0x0b, 0x52, 0x54, 0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x71, 0x75, 0x74, 0x6f, 0x75, 0x74,
	0x69, 0x61, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x65, 0x78,
	0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x0d, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x75, 0x6e,
	0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0d, 0x65, 0x78, 0x63,
	0x6c, 0x75, 0x64, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f,
	0x73, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63,
	0x6f, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x2a, 0x2e, 0x0a, 0x06, 0x4f, 0x53, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x4e, 0x44, 0x52, 0x4f, 0x49, 0x44, 0x10, 0x01, 0x12, 0x07,
	0x0a, 0x03, 0x49, 0x4f, 0x53, 0x10, 0x02, 0x2a, 0x62, 0x0a, 0x0c, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x45, 0x56, 0x49, 0x44,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4d,
	0x45, 0x49, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x44, 0x46, 0x41, 0x10, 0x02, 0x12, 0x0d,
	0x0a, 0x09, 0x41, 0x4e, 0x44, 0x52, 0x4f, 0x49, 0x44, 0x49, 0x44, 0x10, 0x03, 0x12, 0x08, 0x0a,
	0x04, 0x4d, 0x45, 0x49, 0x44, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x41, 0x49, 0x44, 0x10,
	0x05, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x55, 0x49, 0x44, 0x10, 0x06, 0x2a, 0x40, 0x0a, 0x0a, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x49, 0x44,
	0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x49, 0x44, 0x5f, 0x41, 0x42,
	0x41, 0x4e, 0x44, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x42, 0x49, 0x44, 0x5f, 0x45,
	0x58, 0x43, 0x4c, 0x55, 0x44, 0x45, 0x5f, 0x50, 0x41, 0x52, 0x54, 0x10, 0x02, 0x42, 0x21, 0x5a,
	0x1f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x78,
	0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x2f, 0x71, 0x75, 0x74, 0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qutoutiao_rta_proto_rawDescOnce sync.Once
	file_qutoutiao_rta_proto_rawDescData = file_qutoutiao_rta_proto_rawDesc
)

func file_qutoutiao_rta_proto_rawDescGZIP() []byte {
	file_qutoutiao_rta_proto_rawDescOnce.Do(func() {
		file_qutoutiao_rta_proto_rawDescData = protoimpl.X.CompressGZIP(file_qutoutiao_rta_proto_rawDescData)
	})
	return file_qutoutiao_rta_proto_rawDescData
}

var file_qutoutiao_rta_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_qutoutiao_rta_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_qutoutiao_rta_proto_goTypes = []interface{}{
	(OSType)(0),         // 0: qutoutiao.OSType
	(DeviceIdType)(0),   // 1: qutoutiao.DeviceIdType
	(StatusCode)(0),     // 2: qutoutiao.StatusCode
	(*DeviceId)(nil),    // 3: qutoutiao.DeviceId
	(*Device)(nil),      // 4: qutoutiao.Device
	(*RTARequest)(nil),  // 5: qutoutiao.RTARequest
	(*RTAResponse)(nil), // 6: qutoutiao.RTAResponse
}
var file_qutoutiao_rta_proto_depIdxs = []int32{
	1, // 0: qutoutiao.DeviceId.type:type_name -> qutoutiao.DeviceIdType
	0, // 1: qutoutiao.Device.os:type_name -> qutoutiao.OSType
	3, // 2: qutoutiao.Device.dev_id:type_name -> qutoutiao.DeviceId
	4, // 3: qutoutiao.RTARequest.device:type_name -> qutoutiao.Device
	2, // 4: qutoutiao.RTAResponse.status_code:type_name -> qutoutiao.StatusCode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_qutoutiao_rta_proto_init() }
func file_qutoutiao_rta_proto_init() {
	if File_qutoutiao_rta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qutoutiao_rta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qutoutiao_rta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qutoutiao_rta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RTARequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qutoutiao_rta_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RTAResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qutoutiao_rta_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qutoutiao_rta_proto_goTypes,
		DependencyIndexes: file_qutoutiao_rta_proto_depIdxs,
		EnumInfos:         file_qutoutiao_rta_proto_enumTypes,
		MessageInfos:      file_qutoutiao_rta_proto_msgTypes,
	}.Build()
	File_qutoutiao_rta_proto = out.File
	file_qutoutiao_rta_proto_rawDesc = nil
	file_qutoutiao_rta_proto_goTypes = nil
	file_qutoutiao_rta_proto_depIdxs = nil
}
