// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: kuaishou_rta.proto

package kuaishou

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OsType int32

const (
	OsType_UNKNOWN_OS OsType = 0 // 未知类型
	OsType_ANDROID    OsType = 1 // Android
	OsType_IOS        OsType = 2 // iOS
)

// Enum value maps for OsType.
var (
	OsType_name = map[int32]string{
		0: "UNKNOWN_OS",
		1: "ANDROID",
		2: "IOS",
	}
	OsType_value = map[string]int32{
		"UNKNOWN_OS": 0,
		"ANDROID":    1,
		"IOS":        2,
	}
)

func (x OsType) Enum() *OsType {
	p := new(OsType)
	*p = x
	return p
}

func (x OsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OsType) Descriptor() protoreflect.EnumDescriptor {
	return file_kuaishou_rta_proto_enumTypes[0].Descriptor()
}

func (OsType) Type() protoreflect.EnumType {
	return &file_kuaishou_rta_proto_enumTypes[0]
}

func (x OsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OsType.Descriptor instead.
func (OsType) EnumDescriptor() ([]byte, []int) {
	return file_kuaishou_rta_proto_rawDescGZIP(), []int{0}
}

type DeviceType int32

const (
	DeviceType_UNKNOWN_DEVICE DeviceType = 0 // 未知类型
	DeviceType_PHONE          DeviceType = 1 // 手机
	DeviceType_TABLET         DeviceType = 2 // 平板
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "UNKNOWN_DEVICE",
		1: "PHONE",
		2: "TABLET",
	}
	DeviceType_value = map[string]int32{
		"UNKNOWN_DEVICE": 0,
		"PHONE":          1,
		"TABLET":         2,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_kuaishou_rta_proto_enumTypes[1].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_kuaishou_rta_proto_enumTypes[1]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_kuaishou_rta_proto_rawDescGZIP(), []int{1}
}

type Gender int32

const (
	Gender_UNKNOWN_GENDER Gender = 0 // 未知
	Gender_MALE           Gender = 1 // 男
	Gender_FEMALE         Gender = 2 // 女
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "UNKNOWN_GENDER",
		1: "MALE",
		2: "FEMALE",
	}
	Gender_value = map[string]int32{
		"UNKNOWN_GENDER": 0,
		"MALE":           1,
		"FEMALE":         2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_kuaishou_rta_proto_enumTypes[2].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_kuaishou_rta_proto_enumTypes[2]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_kuaishou_rta_proto_rawDescGZIP(), []int{2}
}

type Resp_ResultType int32

const (
	Resp_ALL  Resp_ResultType = 0 // 全部都投
	Resp_NONE Resp_ResultType = 1 // 全部不投
	Resp_PART Resp_ResultType = 2 // 只投一部分
)

// Enum value maps for Resp_ResultType.
var (
	Resp_ResultType_name = map[int32]string{
		0: "ALL",
		1: "NONE",
		2: "PART",
	}
	Resp_ResultType_value = map[string]int32{
		"ALL":  0,
		"NONE": 1,
		"PART": 2,
	}
)

func (x Resp_ResultType) Enum() *Resp_ResultType {
	p := new(Resp_ResultType)
	*p = x
	return p
}

func (x Resp_ResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Resp_ResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_kuaishou_rta_proto_enumTypes[3].Descriptor()
}

func (Resp_ResultType) Type() protoreflect.EnumType {
	return &file_kuaishou_rta_proto_enumTypes[3]
}

func (x Resp_ResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Resp_ResultType.Descriptor instead.
func (Resp_ResultType) EnumDescriptor() ([]byte, []int) {
	return file_kuaishou_rta_proto_rawDescGZIP(), []int{2, 0}
}

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                             // 请求唯一id
	OsType     OsType     `protobuf:"varint,2,opt,name=os_type,json=osType,proto3,enum=kuaishou.OsType" json:"os_type,omitempty"`                 // 系统
	DidMd5     string     `protobuf:"bytes,3,opt,name=did_md5,json=didMd5,proto3" json:"did_md5,omitempty"`                                       // 安卓为 imei_md5，ios 为 idfa_md5
	TagId      string     `protobuf:"bytes,4,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`                                          // 广告位 ID
	Gender     Gender     `protobuf:"varint,5,opt,name=gender,proto3,enum=kuaishou.Gender" json:"gender,omitempty"`                               // 性别
	Age        int32      `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`                                                          // 年龄段, 0(<18), 1(18~23), 2(24~30), 3(31~40), 4(41~49), 5(>50)
	City       string     `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`                                                         // 城市
	DeviceType DeviceType `protobuf:"varint,8,opt,name=device_type,json=deviceType,proto3,enum=kuaishou.DeviceType" json:"device_type,omitempty"` // 机型
	Model      string     `protobuf:"bytes,9,opt,name=model,proto3" json:"model,omitempty"`                                                       // 设备型号
	Oaid       string     `protobuf:"bytes,10,opt,name=oaid,proto3" json:"oaid,omitempty"`                                                        //设备oaid
	UserAgent  string     `protobuf:"bytes,11,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`                             //请求UA信息
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuaishou_rta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_kuaishou_rta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_kuaishou_rta_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Req) GetOsType() OsType {
	if x != nil {
		return x.OsType
	}
	return OsType_UNKNOWN_OS
}

func (x *Req) GetDidMd5() string {
	if x != nil {
		return x.DidMd5
	}
	return ""
}

func (x *Req) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *Req) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_UNKNOWN_GENDER
}

func (x *Req) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Req) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Req) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_UNKNOWN_DEVICE
}

func (x *Req) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Req) GetOaid() string {
	if x != nil {
		return x.Oaid
	}
	return ""
}

func (x *Req) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type RtaResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // 账号id, 必填
	UnitId    uint64  `protobuf:"varint,3,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`          // 广告组id, 不填代表所有广告组
	BidRatio  float64 `protobuf:"fixed64,4,opt,name=bid_ratio,json=bidRatio,proto3" json:"bid_ratio,omitempty"`   //动态出价系数
}

func (x *RtaResult) Reset() {
	*x = RtaResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuaishou_rta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtaResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtaResult) ProtoMessage() {}

func (x *RtaResult) ProtoReflect() protoreflect.Message {
	mi := &file_kuaishou_rta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtaResult.ProtoReflect.Descriptor instead.
func (*RtaResult) Descriptor() ([]byte, []int) {
	return file_kuaishou_rta_proto_rawDescGZIP(), []int{1}
}

func (x *RtaResult) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *RtaResult) GetUnitId() uint64 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *RtaResult) GetBidRatio() float64 {
	if x != nil {
		return x.BidRatio
	}
	return 0
}

type Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                  // 请求唯一id
	ResultType Resp_ResultType `protobuf:"varint,2,opt,name=result_type,json=resultType,proto3,enum=kuaishou.Resp_ResultType" json:"result_type,omitempty"` // 结果类型, 等于PART时, result必填
	Result     []*RtaResult    `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty"`                                                          // 允许投放的广告列表, 如有重复取并集
	BidRatio   float64         `protobuf:"fixed64,4,opt,name=bid_ratio,json=bidRatio,proto3" json:"bid_ratio,omitempty"`                                    // result_type=ALL时的动态出价系数
	Label      []string        `protobuf:"bytes,5,rep,name=label,proto3" json:"label,omitempty"`                                                            //dsp传入的标签。数据合作需求
	RefuseTime uint32          `protobuf:"varint,6,opt,name=refuse_time,json=refuseTime,proto3" json:"refuse_time,omitempty"`                               //拒绝时间
	CacheTime  uint32          `protobuf:"varint,7,opt,name=cache_time,json=cacheTime,proto3" json:"cache_time,omitempty"`                                  //缓存时间
}

func (x *Resp) Reset() {
	*x = Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuaishou_rta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_kuaishou_rta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_kuaishou_rta_proto_rawDescGZIP(), []int{2}
}

func (x *Resp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resp) GetResultType() Resp_ResultType {
	if x != nil {
		return x.ResultType
	}
	return Resp_ALL
}

func (x *Resp) GetResult() []*RtaResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Resp) GetBidRatio() float64 {
	if x != nil {
		return x.BidRatio
	}
	return 0
}

func (x *Resp) GetLabel() []string {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *Resp) GetRefuseTime() uint32 {
	if x != nil {
		return x.RefuseTime
	}
	return 0
}

func (x *Resp) GetCacheTime() uint32 {
	if x != nil {
		return x.CacheTime
	}
	return 0
}

var File_kuaishou_rta_proto protoreflect.FileDescriptor

var file_kuaishou_rta_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6b, 0x75, 0x61, 0x69, 0x73, 0x68, 0x6f, 0x75, 0x5f, 0x72, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6b, 0x75, 0x61, 0x69, 0x73, 0x68, 0x6f, 0x75, 0x22, 0xc0,
	0x02, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x07, 0x6f, 0x73, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6b, 0x75, 0x61, 0x69, 0x73, 0x68,
	0x6f, 0x75, 0x2e, 0x4f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6f, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x69, 0x64, 0x5f, 0x6d, 0x64, 0x35, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x64, 0x4d, 0x64, 0x35, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49,
	0x64, 0x12, 0x28, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x6b, 0x75, 0x61, 0x69, 0x73, 0x68, 0x6f, 0x75, 0x2e, 0x47, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x35, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6b, 0x75, 0x61, 0x69, 0x73, 0x68, 0x6f,
	0x75, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x6f, 0x61, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x61,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x22, 0x60, 0x0a, 0x09, 0x52, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x69, 0x64, 0x5f, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x62, 0x69, 0x64, 0x52, 0x61,
	0x74, 0x69, 0x6f, 0x22, 0x9d, 0x02, 0x0a, 0x04, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x0b,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x6b, 0x75, 0x61, 0x69, 0x73, 0x68, 0x6f, 0x75, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6b, 0x75, 0x61, 0x69, 0x73,
	0x68, 0x6f, 0x75, 0x2e, 0x52, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x69, 0x64, 0x5f, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x62, 0x69, 0x64, 0x52, 0x61, 0x74,
	0x69, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x66, 0x75,
	0x73, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x72,
	0x65, 0x66, 0x75, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x41, 0x52,
	0x54, 0x10, 0x02, 0x2a, 0x2e, 0x0a, 0x06, 0x4f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a,
	0x0a, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x4f, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x41, 0x4e, 0x44, 0x52, 0x4f, 0x49, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4f,
	0x53, 0x10, 0x02, 0x2a, 0x37, 0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x44, 0x45, 0x56,
	0x49, 0x43, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x48, 0x4f, 0x4e, 0x45, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x54, 0x10, 0x02, 0x2a, 0x32, 0x0a, 0x06,
	0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x5f, 0x47, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41,
	0x4c, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x02,
	0x42, 0x20, 0x5a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x2f, 0x6b, 0x75, 0x61, 0x69, 0x73, 0x68,
	0x6f, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kuaishou_rta_proto_rawDescOnce sync.Once
	file_kuaishou_rta_proto_rawDescData = file_kuaishou_rta_proto_rawDesc
)

func file_kuaishou_rta_proto_rawDescGZIP() []byte {
	file_kuaishou_rta_proto_rawDescOnce.Do(func() {
		file_kuaishou_rta_proto_rawDescData = protoimpl.X.CompressGZIP(file_kuaishou_rta_proto_rawDescData)
	})
	return file_kuaishou_rta_proto_rawDescData
}

var file_kuaishou_rta_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_kuaishou_rta_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kuaishou_rta_proto_goTypes = []interface{}{
	(OsType)(0),          // 0: kuaishou.OsType
	(DeviceType)(0),      // 1: kuaishou.DeviceType
	(Gender)(0),          // 2: kuaishou.Gender
	(Resp_ResultType)(0), // 3: kuaishou.Resp.ResultType
	(*Req)(nil),          // 4: kuaishou.Req
	(*RtaResult)(nil),    // 5: kuaishou.RtaResult
	(*Resp)(nil),         // 6: kuaishou.Resp
}
var file_kuaishou_rta_proto_depIdxs = []int32{
	0, // 0: kuaishou.Req.os_type:type_name -> kuaishou.OsType
	2, // 1: kuaishou.Req.gender:type_name -> kuaishou.Gender
	1, // 2: kuaishou.Req.device_type:type_name -> kuaishou.DeviceType
	3, // 3: kuaishou.Resp.result_type:type_name -> kuaishou.Resp.ResultType
	5, // 4: kuaishou.Resp.result:type_name -> kuaishou.RtaResult
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_kuaishou_rta_proto_init() }
func file_kuaishou_rta_proto_init() {
	if File_kuaishou_rta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kuaishou_rta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuaishou_rta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtaResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuaishou_rta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kuaishou_rta_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kuaishou_rta_proto_goTypes,
		DependencyIndexes: file_kuaishou_rta_proto_depIdxs,
		EnumInfos:         file_kuaishou_rta_proto_enumTypes,
		MessageInfos:      file_kuaishou_rta_proto_msgTypes,
	}.Build()
	File_kuaishou_rta_proto = out.File
	file_kuaishou_rta_proto_rawDesc = nil
	file_kuaishou_rta_proto_goTypes = nil
	file_kuaishou_rta_proto_depIdxs = nil
}
